### ISSUE TITLE
Version should reset when repo change

### ISSUE THREAD

**Issue by infeng** [ant-design/antd-issue-helper#2]
I change version first, then change repo, but the version not reset.

![bug21](https://cloud.githubusercontent.com/assets/16483610/24490162/f73d8ee0-1553-11e7-831f-d72752b28562.png)

**Comment by yesmeck** [comment]
Check your console, did you get any error?

**Comment by infeng** [comment]
No error.

**Comment by yesmeck** [comment]
One possible reason is you reached the GitHub api's rate limit.

**Comment by infeng** [comment]
GitHub api is well, I means you should reset version`s current value when repo change.

**Comment by yesmeck** [comment]
I did... https://github.com/ant-design/antd-issue-helper/blob/master/src/IssueForm.tsx#L84-L86

**Comment by infeng** [comment]
add

**Comment by infeng** [comment]
Add this in https://github.com/ant-design/antd-issue-helper/blob/master/src/IssueForm.tsx#L84 maybe better.
```javascript
const { form } = this.props;
form.resetFields(['version']);
```

**Comment by yesmeck** [comment]
Oh, got your point!

**Comment by infeng** [comment]
:satisfied: I didn't express clearly.
