### ISSUE TITLE
提交完毕显示414 Request-URI Too Large并且preview时显示不正常

### ISSUE THREAD

**Issue by jasminecjc** [ant-design/antd-issue-helper#3]
<img width="860" alt="screen shot 2017-06-15 at 7 24 26 pm" src="https://user-images.githubusercontent.com/13568376/27179491-6d219c3e-5201-11e7-9eb6-f26355c71348.png">
<img width="848" alt="screen shot 2017-06-15 at 7 24 57 pm" src="https://user-images.githubusercontent.com/13568376/27179496-733910ca-5201-11e7-84e7-291ff5522e73.png">

**Comment by yesmeck** [comment]
Issue 里贴那么大堆业务代码没啥意义，最好是给最简化的重现 demo 链接。

**Comment by jasminecjc** [comment]
不是业务代码的问题，是下面上传的图片过大然后图片超出了那个modal的size，这个是样式的问题
